version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    environment:
      - MONGO_INITDB_REPLICA_SET=rs0
    command: ["--replSet", "rs0"]
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
